import React, { createContext, useState, useContext, useEffect } from 'react';

// 📚 دیکشنری ترجمه‌ها
const translations = {
  fa: {
    appName: 'استخراج سکه',
    welcome: 'به Coin Mining خوش آمدید',
    choose_language: 'انتخاب زبان',
    rules_title: '📋 قوانین و راهنمایی',
    later: 'باشه بعداً سر میزنم',
    go_to_rules: 'رفتن به قوانین',
    home: 'خانه',
    wallet: 'کیف پول',
    missions: 'ماموریت',
    profile: 'پروفایل',
    vip: 'VIP',
    referral: 'دعوت',
    about: 'درباره ما',
    support: 'پشتیبانی',
    settings: 'تنظیمات',
    user_panel: 'پنل کاربری',
    hello: 'سلام 👋',
    dear_user: 'کاربر عزیز',
    total_balance: 'موجودی کل',
    level: 'سطح',
    logged_in: 'وارد شده',
    select_coin: '💎 انتخاب ارز برای استخراج',
    click_to_see_details: 'روی هر ارز کلیک کنید تا جزئیات را ببینید',
    live_prices: '📊 قیمت‌های لحظه‌ای',
    last_update: 'آخرین بروزرسانی',
    wallet_title: '💳 کیف پول',
    connect_wallet: '🔗 اتصال کیف پول TON',
    connecting: '⏳ در حال اتصال...',
    your_address: 'آدرس کیف پول شما',
    wallet_balance: 'موجودی کیف پول',
    disconnect: 'قطع اتصال',
    payment: '💳 پرداخت درون برنامه‌ای',
    amount: 'مبلغ به TON',
    pay: 'پرداخت',
    secure_payment: '🔒 پرداخت شما به کیف پول امن برنامه واریز میشود',
    history: '📜 تاریخچه تراکنش‌ها',
    no_transactions: 'هیچ تراکنشی ثبت نشده است',
    free_miner: '⚡ ماینر رایگان',
    active: 'فعال',
    mining_power: 'قدرت ماینینگ',
    start: 'شروع ▶',
    stop: 'توقف ⏹',
    mining: 'در حال ماینینگ...',
    boost: '🔥 فعال‌سازی سرعت دو برابر (۳۰ دقیقه)',
    rent_miners: '🏗️ ماینرهای اجاره‌ای',
    each_miner_30_days: 'هر ماینر ۳۰ روز فعالیت می‌کند',
    rent: 'اجاره',
    convert: '🔄 تبدیل به TON',
    convert_rate: 'نرخ لحظه‌ای',
    minimum_convert: 'حداقل موجودی قابل تبدیل',
    vip_club: '👑 باشگاه VIP',
    current_level: 'سطح فعلی',
    cost: 'هزینه',
    upgrade: 'ارتقا',
    locked: '🔒 قفل',
    active_badge: 'فعال',
    processing: '⏳ در حال پرداخت...',
    starter: 'Starter',
    starter_plus: 'Starter Plus',
    galaxy: 'Galaxy',
    nova: 'Nova',
    daily_missions: '📅 مأموریت‌های روزانه',
    current_streak: 'زنجیره فعلی',
    day: 'روز',
    reward: 'جایزه',
    claim: 'دریافت 🎁',
    claimed: '✅ دریافت شد',
    locked_mission: '🔒 قفل',
    available: '✅ قابل دریافت',
    streak_reset: '⏰ زنجیره شما به دلیل عدم فعالیت ریست شد!',
    referral_title: '👥 زیرمجموعه‌گیری',
    referral_text: 'با معرفی به هر یک از دوستانت ۱ TON جایزه بگیر و ۱۰٪ از واریزهای دوستانت را شریک شو',
    copy_link: '📋 کپی لینک',
    share: 'اشتراک‌گذاری',
    telegram: '📨 تلگرام',
    whatsapp: '💬 واتساپ',
    instagram: '📱 اینستاگرام',
    invited_friends: 'دوستان دعوت شده',
    no_referrals: 'هنوز کسی دعوت نشده است',
    profile_title: '👤 پروفایل',
    edit_profile: '👤 ویرایش پروفایل',
    username: 'نام کاربری',
    email: 'ایمیل',
    save_changes: '💾 ذخیره تغییرات',
    change_password: '🔒 تغییر رمز عبور',
    current_password: 'رمز عبور فعلی',
    new_password: 'رمز عبور جدید',
    settings_title: '⚙️ تنظیمات',
    change_language: '🌍 تغییر زبان',
    rules_guidelines: '📋 قوانین و راهنمایی',
    about_us: 'ℹ️ درباره ما',
    feedback: '💬 بازخورد',
    send_feedback: '📤 ارسال بازخورد',
    feedback_sent: '✅ ارسال شد',
    feedback_placeholder: 'نظر، پیشنهاد یا انتقاد خود را بنویسید...',
    admin_panel: '🛠️ پنل مدیریت',
    admin_login: 'پنل مدیریت',
    login: '🔑 ورود به پنل مدیریت',
    username_label: 'نام کاربری',
    password_label: 'رمز عبور',
    enter_username: 'نام کاربری را وارد کنید',
    enter_password: 'رمز عبور را وارد کنید',
    checking: '⏳ در حال بررسی...',
    invalid_credentials: '❌ نام کاربری یا رمز عبور اشتباه است!',
    admin_only: '⚠️ این بخش فقط برای مدیران سیستم است',
    logout: '🚪 خروج',
    support_title: '🎫 سیستم پشتیبانی',
    new_ticket: '✏️ تیکت جدید',
    ticket_list: '📋 لیست تیکت‌ها',
    subject: 'موضوع',
    message: 'پیام',
    priority: 'اولویت',
    low: 'کم',
    normal: 'معمولی',
    high: 'بالا',
    urgent: 'فوری',
    submit_ticket: '📤 ارسال تیکت',
    no_tickets: '📭 هیچ تیکتی ثبت نشده است',
    open: 'باز',
    closed: 'بسته',
    pending: 'در انتظار',
    about_title: 'ℹ️ درباره ما',
    mission: '🎯 ماموریت ما',
    features: '✨ ویژگی‌های کلیدی',
    contact: '📬 ارتباط با ما',
    email_label: 'ایمیل',
    website: 'وبسایت',
    telegram_bot: 'تلگرام',
    version: 'نسخه',
    copyright: 'کلیه حقوق محفوظ است',
    sync_success: '✅ داده‌ها با سرور همگام‌سازی شد',
    sync_error: '❌ خطا در همگام‌سازی',
    logout_success: '👋 شما از حساب خود خارج شدید',
    language_changed: '🌍 زبان با موفقیت تغییر کرد',
    payment_success: 'پرداخت با موفقیت انجام شد',
    reward_claimed: 'پاداش دریافت شد'
  },
  en: {
    appName: 'Coin Mining',
    welcome: 'Welcome to Coin Mining',
    choose_language: 'Choose Language',
    rules_title: '📋 Rules & Guidelines',
    later: 'I\'ll check later',
    go_to_rules: 'Go to Rules',
    home: 'Home',
    wallet: 'Wallet',
    missions: 'Missions',
    profile: 'Profile',
    vip: 'VIP',
    referral: 'Referrals',
    about: 'About',
    support: 'Support',
    settings: 'Settings',
    user_panel: 'User Panel',
    hello: 'Hello 👋',
    dear_user: 'Dear User',
    total_balance: 'Total Balance',
    level: 'Level',
    logged_in: 'Logged In',
    select_coin: '💎 Select a Cryptocurrency to Mine',
    click_to_see_details: 'Click on any coin to see details',
    live_prices: '📊 Live Prices',
    last_update: 'Last Update',
    wallet_title: '💳 Wallet',
    connect_wallet: '🔗 Connect TON Wallet',
    connecting: '⏳ Connecting...',
    your_address: 'Your Wallet Address',
    wallet_balance: 'Wallet Balance',
    disconnect: 'Disconnect',
    payment: '💳 In-App Payment',
    amount: 'Amount in TON',
    pay: 'Pay',
    secure_payment: '🔒 Your payment is securely processed',
    history: '📜 Transaction History',
    no_transactions: 'No transactions recorded',
    free_miner: '⚡ Free Miner',
    active: 'Active',
    mining_power: 'Mining Power',
    start: 'Start ▶',
    stop: 'Stop ⏹',
    mining: 'Mining...',
    boost: '🔥 Activate Double Speed (30 min)',
    rent_miners: '🏗️ Rent Miners',
    each_miner_30_days: 'Each miner operates for 30 days',
    rent: 'Rent',
    convert: '🔄 Convert to TON',
    convert_rate: 'Live Rate',
    minimum_convert: 'Minimum convertible balance',
    vip_club: '👑 VIP Club',
    current_level: 'Current Level',
    cost: 'Cost',
    upgrade: 'Upgrade',
    locked: '🔒 Locked',
    active_badge: 'Active',
    processing: '⏳ Processing...',
    starter: 'Starter',
    starter_plus: 'Starter Plus',
    galaxy: 'Galaxy',
    nova: 'Nova',
    daily_missions: '📅 Daily Missions',
    current_streak: 'Current Streak',
    day: 'Day',
    reward: 'Reward',
    claim: 'Claim 🎁',
    claimed: '✅ Claimed',
    locked_mission: '🔒 Locked',
    available: '✅ Available',
    streak_reset: '⏰ Your streak has been reset due to inactivity!',
    referral_title: '👥 Referrals',
    referral_text: 'Invite friends and get 1 TON reward and 10% of their deposits',
    copy_link: '📋 Copy Link',
    share: 'Share',
    telegram: '📨 Telegram',
    whatsapp: '💬 WhatsApp',
    instagram: '📱 Instagram',
    invited_friends: 'Invited Friends',
    no_referrals: 'No one has been invited yet',
    profile_title: '👤 Profile',
    edit_profile: '👤 Edit Profile',
    username: 'Username',
    email: 'Email',
    save_changes: '💾 Save Changes',
    change_password: '🔒 Change Password',
    current_password: 'Current Password',
    new_password: 'New Password',
    settings_title: '⚙️ Settings',
    change_language: '🌍 Change Language',
    rules_guidelines: '📋 Rules & Guidelines',
    about_us: 'ℹ️ About Us',
    feedback: '💬 Feedback',
    send_feedback: '📤 Send Feedback',
    feedback_sent: '✅ Sent',
    feedback_placeholder: 'Write your feedback...',
    admin_panel: '🛠️ Admin Panel',
    admin_login: 'Admin Panel',
    login: '🔑 Login',
    username_label: 'Username',
    password_label: 'Password',
    enter_username: 'Enter username',
    enter_password: 'Enter password',
    checking: '⏳ Checking...',
    invalid_credentials: '❌ Invalid username or password!',
    admin_only: '⚠️ This section is for administrators only',
    logout: '🚪 Logout',
    support_title: '🎫 Support',
    new_ticket: '✏️ New Ticket',
    ticket_list: '📋 Ticket List',
    subject: 'Subject',
    message: 'Message',
    priority: 'Priority',
    low: 'Low',
    normal: 'Normal',
    high: 'High',
    urgent: 'Urgent',
    submit_ticket: '📤 Submit Ticket',
    no_tickets: '📭 No tickets found',
    open: 'Open',
    closed: 'Closed',
    pending: 'Pending',
    about_title: 'ℹ️ About Us',
    mission: '🎯 Our Mission',
    features: '✨ Key Features',
    contact: '📬 Contact Us',
    email_label: 'Email',
    website: 'Website',
    telegram_bot: 'Telegram',
    version: 'Version',
    copyright: 'All rights reserved',
    sync_success: '✅ Data synced successfully',
    sync_error: '❌ Sync error',
    logout_success: '👋 You have been logged out',
    language_changed: '🌍 Language changed successfully',
    payment_success: 'Payment successful',
    reward_claimed: 'Reward claimed'
  },
  tr: {
    appName: 'Coin Madenciliği',
    welcome: 'Coin Mining\'e Hoş Geldiniz',
    choose_language: 'Dil Seçin',
    home: 'Ana Sayfa',
    wallet: 'Cüzdan',
    missions: 'Görevler',
    profile: 'Profil',
    vip: 'VIP',
    referral: 'Davetler',
    about: 'Hakkımızda',
    support: 'Destek',
    settings: 'Ayarlar',
    user_panel: 'Kullanıcı Paneli',
    hello: 'Merhaba 👋',
    dear_user: 'Değerli Kullanıcı',
    total_balance: 'Toplam Bakiye',
    level: 'Seviye',
    logged_in: 'Giriş Yapıldı',
    select_coin: '💎 Madencilik İçin Kripto Para Seçin',
    live_prices: '📊 Canlı Fiyatlar',
    connect_wallet: '🔗 TON Cüzdan Bağla',
    wallet_balance: 'Cüzdan Bakiyesi',
    disconnect: 'Bağlantıyı Kes',
    payment: '💳 Uygulama İçi Ödeme',
    pay: 'Öde',
    history: '📜 İşlem Geçmişi',
    free_miner: '⚡ Ücretsiz Madenci',
    active: 'Aktif',
    start: 'Başlat ▶',
    stop: 'Durdur ⏹',
    rent_miners: '🏗️ Kiralık Madenciler',
    rent: 'Kirala',
    convert: '🔄 TON\'a Dönüştür',
    vip_club: '👑 VIP Kulübü',
    current_level: 'Mevcut Seviye',
    cost: 'Maliyet',
    upgrade: 'Yükselt',
    locked: '🔒 Kilitli',
    daily_missions: '📅 Günlük Görevler',
    current_streak: 'Mevcut Seri',
    day: 'Gün',
    reward: 'Ödül',
    claim: 'Al 🎁',
    claimed: '✅ Alındı',
    referral_title: '👥 Davetler',
    referral_text: 'Arkadaşlarını davet et ve 1 TON ödül ve yatırımlarının %10\'unu kazan',
    copy_link: '📋 Bağlantıyı Kopyala',
    share: 'Paylaş',
    telegram: '📨 Telegram',
    whatsapp: '💬 WhatsApp',
    instagram: '📱 Instagram',
    profile_title: '👤 Profil',
    username: 'Kullanıcı Adı',
    email: 'E-posta',
    save_changes: '💾 Değişiklikleri Kaydet',
    change_password: '🔒 Şifre Değiştir',
    settings_title: '⚙️ Ayarlar',
    change_language: '🌍 Dili Değiştir',
    about_us: 'ℹ️ Hakkımızda',
    feedback: '💬 Geri Bildirim',
    send_feedback: '📤 Geri Bildirim Gönder',
    admin_panel: '🛠️ Yönetim Paneli',
    admin_login: 'Yönetim Paneli',
    login: '🔑 Giriş Yap',
    username_label: 'Kullanıcı Adı',
    password_label: 'Şifre',
    enter_username: 'Kullanıcı adını girin',
    enter_password: 'Şifrenizi girin',
    invalid_credentials: '❌ Geçersiz kullanıcı adı veya şifre!',
    logout: '🚪 Çıkış Yap',
    support_title: '🎫 Destek',
    new_ticket: '✏️ Yeni Talep',
    subject: 'Konu',
    message: 'Mesaj',
    priority: 'Öncelik',
    low: 'Düşük',
    normal: 'Normal',
    high: 'Yüksek',
    urgent: 'Acil',
    submit_ticket: '📤 Talep Gönder',
    no_tickets: '📭 Talep bulunamadı',
    open: 'Açık',
    closed: 'Kapalı',
    pending: 'Beklemede',
    about_title: 'ℹ️ Hakkımızda',
    mission: '🎯 Misyonumuz',
    features: '✨ Temel Özellikler',
    contact: '📬 Bize Ulaşın',
    email_label: 'E-posta',
    website: 'Web Sitesi',
    telegram_bot: 'Telegram',
    version: 'Sürüm',
    copyright: 'Tüm hakları saklıdır',
    sync_success: '✅ Veriler başarıyla senkronize edildi',
    sync_error: '❌ Senkronizasyon hatası',
    logout_success: '👋 Çıkış yaptınız',
    language_changed: '🌍 Dil başarıyla değiştirildi',
    payment_success: 'Ödeme başarılı',
    reward_claimed: 'Ödül alındı'
  },
  ru: {
    appName: 'Coin Mining',
    welcome: 'Добро пожаловать в Coin Mining',
    choose_language: 'Выберите язык',
    home: 'Главная',
    wallet: 'Кошелек',
    missions: 'Миссии',
    profile: 'Профиль',
    vip: 'VIP',
    referral: 'Рефералы',
    about: 'О нас',
    support: 'Поддержка',
    settings: 'Настройки',
    user_panel: 'Панель пользователя',
    hello: 'Привет 👋',
    dear_user: 'Уважаемый пользователь',
    total_balance: 'Общий баланс',
    level: 'Уровень',
    logged_in: 'Вошли',
    select_coin: '💎 Выберите криптовалюту для майнинга',
    live_prices: '📊 Актуальные цены',
    connect_wallet: '🔗 Подключить TON кошелек',
    wallet_balance: 'Баланс кошелька',
    disconnect: 'Отключить',
    payment: '💳 Оплата в приложении',
    pay: 'Оплатить',
    history: '📜 История транзакций',
    free_miner: '⚡ Бесплатный майнер',
    active: 'Активен',
    start: 'Старт ▶',
    stop: 'Стоп ⏹',
    rent_miners: '🏗️ Аренда майнеров',
    rent: 'Арендовать',
    convert: '🔄 Конвертировать в TON',
    vip_club: '👑 VIP клуб',
    current_level: 'Текущий уровень',
    cost: 'Стоимость',
    upgrade: 'Повысить',
    locked: '🔒 Заблокировано',
    daily_missions: '📅 Ежедневные миссии',
    current_streak: 'Текущая серия',
    day: 'День',
    reward: 'Награда',
    claim: 'Получить 🎁',
    claimed: '✅ Получено',
    referral_title: '👥 Рефералы',
    referral_text: 'Приглашайте друзей и получайте 1 TON награды и 10% от их депозитов',
    copy_link: '📋 Копировать ссылку',
    share: 'Поделиться',
    telegram: '📨 Telegram',
    whatsapp: '💬 WhatsApp',
    instagram: '📱 Instagram',
    profile_title: '👤 Профиль',
    username: 'Имя пользователя',
    email: 'Email',
    save_changes: '💾 Сохранить изменения',
    change_password: '🔒 Сменить пароль',
    settings_title: '⚙️ Настройки',
    change_language: '🌍 Сменить язык',
    about_us: 'ℹ️ О нас',
    feedback: '💬 Обратная связь',
    send_feedback: '📤 Отправить отзыв',
    admin_panel: '🛠️ Панель администратора',
    admin_login: 'Панель администратора',
    login: '🔑 Войти',
    username_label: 'Имя пользователя',
    password_label: 'Пароль',
    enter_username: 'Введите имя пользователя',
    enter_password: 'Введите пароль',
    invalid_credentials: '❌ Неверное имя пользователя или пароль!',
    logout: '🚪 Выйти',
    support_title: '🎫 Поддержка',
    new_ticket: '✏️ Новый запрос',
    subject: 'Тема',
    message: 'Сообщение',
    priority: 'Приоритет',
    low: 'Низкий',
    normal: 'Обычный',
    high: 'Высокий',
    urgent: 'Срочный',
    submit_ticket: '📤 Отправить запрос',
    no_tickets: '📭 Запросов не найдено',
    open: 'Открыт',
    closed: 'Закрыт',
    pending: 'В ожидании',
    about_title: 'ℹ️ О нас',
    mission: '🎯 Наша миссия',
    features: '✨ Ключевые особенности',
    contact: '📬 Свяжитесь с нами',
    email_label: 'Email',
    website: 'Веб-сайт',
    telegram_bot: 'Telegram',
    version: 'Версия',
    copyright: 'Все права защищены',
    sync_success: '✅ Данные успешно синхронизированы',
    sync_error: '❌ Ошибка синхронизации',
    logout_success: '👋 Вы вышли из системы',
    language_changed: '🌍 Язык успешно изменен',
    payment_success: 'Оплата успешна',
    reward_claimed: 'Награда получена'
  },
  ar: {
    appName: 'تعدين العملات',
    welcome: 'مرحباً بك في Coin Mining',
    choose_language: 'اختر اللغة',
    home: 'الرئيسية',
    wallet: 'المحفظة',
    missions: 'المهام',
    profile: 'الملف الشخصي',
    vip: 'VIP',
    referral: 'الدعوات',
    about: 'معلومات عنا',
    support: 'الدعم',
    settings: 'الإعدادات',
    user_panel: 'لوحة المستخدم',
    hello: 'مرحباً 👋',
    dear_user: 'عزيزي المستخدم',
    total_balance: 'الرصيد الإجمالي',
    level: 'المستوى',
    logged_in: 'تم تسجيل الدخول',
    select_coin: '💎 اختر عملة للتعدين',
    live_prices: '📊 الأسعار لحظية',
    connect_wallet: '🔗 ربط محفظة TON',
    wallet_balance: 'رصيد المحفظة',
    disconnect: 'قطع الاتصال',
    payment: '💳 دفع داخل التطبيق',
    pay: 'ادفع',
    history: '📜 سجل المعاملات',
    free_miner: '⚡ جهاز تعدين مجاني',
    active: 'نشط',
    start: 'ابدأ ▶',
    stop: 'إيقاف ⏹',
    rent_miners: '🏗️ تأجير أجهزة التعدين',
    rent: 'استئجار',
    convert: '🔄 تحويل إلى TON',
    vip_club: '👑 نادي VIP',
    current_level: 'المستوى الحالي',
    cost: 'التكلفة',
    upgrade: 'ترقية',
    locked: '🔒 مقفل',
    daily_missions: '📅 المهام اليومية',
    current_streak: 'السلسلة الحالية',
    day: 'يوم',
    reward: 'مكافأة',
    claim: 'استلام 🎁',
    claimed: '✅ تم الاستلام',
    referral_title: '👥 الدعوات',
    referral_text: 'ادعُ أصدقاءك واحصل على ١ TON مكافأة و ١٠٪ من إيداعاتهم',
    copy_link: '📋 نسخ الرابط',
    share: 'مشاركة',
    telegram: '📨 تيليجرام',
    whatsapp: '💬 واتساب',
    instagram: '📱 إنستغرام',
    profile_title: '👤 الملف الشخصي',
    username: 'اسم المستخدم',
    email: 'البريد الإلكتروني',
    save_changes: '💾 حفظ التغييرات',
    change_password: '🔒 تغيير كلمة المرور',
    settings_title: '⚙️ الإعدادات',
    change_language: '🌍 تغيير اللغة',
    about_us: 'ℹ️ معلومات عنا',
    feedback: '💬 ملاحظات',
    send_feedback: '📤 إرسال الملاحظات',
    admin_panel: '🛠️ لوحة الإدارة',
    admin_login: 'لوحة الإدارة',
    login: '🔑 تسجيل الدخول',
    username_label: 'اسم المستخدم',
    password_label: 'كلمة المرور',
    enter_username: 'أدخل اسم المستخدم',
    enter_password: 'أدخل كلمة المرور',
    invalid_credentials: '❌ اسم المستخدم أو كلمة المرور غير صحيحة!',
    logout: '🚪 تسجيل الخروج',
    support_title: '🎫 الدعم',
    new_ticket: '✏️ تذكرة جديدة',
    subject: 'الموضوع',
    message: 'الرسالة',
    priority: 'الأولوية',
    low: 'منخفضة',
    normal: 'عادية',
    high: 'عالية',
    urgent: 'عاجلة',
    submit_ticket: '📤 إرسال التذكرة',
    no_tickets: '📭 لا توجد تذاكر',
    open: 'مفتوحة',
    closed: 'مغلقة',
    pending: 'قيد الانتظار',
    about_title: 'ℹ️ معلومات عنا',
    mission: '🎯 مهمتنا',
    features: '✨ الميزات الرئيسية',
    contact: '📬 اتصل بنا',
    email_label: 'البريد الإلكتروني',
    website: 'الموقع الإلكتروني',
    telegram_bot: 'تيليجرام',
    version: 'الإصدار',
    copyright: 'جميع الحقوق محفوظة',
    sync_success: '✅ تمت مزامنة البيانات بنجاح',
    sync_error: '❌ خطأ في المزامنة',
    logout_success: '👋 تم تسجيل الخروج',
    language_changed: '🌍 تم تغيير اللغة بنجاح',
    payment_success: 'تم الدفع بنجاح',
    reward_claimed: 'تم استلام المكافأة'
  },
  es: {
    appName: 'Coin Mining',
    welcome: 'Bienvenido a Coin Mining',
    choose_language: 'Seleccionar idioma',
    home: 'Inicio',
    wallet: 'Cartera',
    missions: 'Misiones',
    profile: 'Perfil',
    vip: 'VIP',
    referral: 'Referidos',
    about: 'Acerca de',
    support: 'Soporte',
    settings: 'Ajustes',
    user_panel: 'Panel de Usuario',
    hello: 'Hola 👋',
    dear_user: 'Estimado Usuario',
    total_balance: 'Saldo Total',
    level: 'Nivel',
    logged_in: 'Conectado',
    select_coin: '💎 Seleccione una Criptomoneda para Minar',
    live_prices: '📊 Precios en Vivo',
    connect_wallet: '🔗 Conectar Cartera TON',
    wallet_balance: 'Saldo de Cartera',
    disconnect: 'Desconectar',
    payment: '💳 Pago en la App',
    pay: 'Pagar',
    history: '📜 Historial de Transacciones',
    free_miner: '⚡ Minero Gratuito',
    active: 'Activo',
    start: 'Iniciar ▶',
    stop: 'Detener ⏹',
    rent_miners: '🏗️ Alquilar Mineros',
    rent: 'Alquilar',
    convert: '🔄 Convertir a TON',
    vip_club: '👑 Club VIP',
    current_level: 'Nivel Actual',
    cost: 'Costo',
    upgrade: 'Mejorar',
    locked: '🔒 Bloqueado',
    daily_missions: '📅 Misiones Diarias',
    current_streak: 'Racha Actual',
    day: 'Día',
    reward: 'Recompensa',
    claim: 'Reclamar 🎁',
    claimed: '✅ Reclamado',
    referral_title: '👥 Referidos',
    referral_text: 'Invita amigos y obtén 1 TON de recompensa y el 10% de sus depósitos',
    copy_link: '📋 Copiar Enlace',
    share: 'Compartir',
    telegram: '📨 Telegram',
    whatsapp: '💬 WhatsApp',
    instagram: '📱 Instagram',
    profile_title: '👤 Perfil',
    username: 'Nombre de Usuario',
    email: 'Correo Electrónico',
    save_changes: '💾 Guardar Cambios',
    change_password: '🔒 Cambiar Contraseña',
    settings_title: '⚙️ Ajustes',
    change_language: '🌍 Cambiar Idioma',
    about_us: 'ℹ️ Acerca de Nosotros',
    feedback: '💬 Comentarios',
    send_feedback: '📤 Enviar Comentarios',
    admin_panel: '🛠️ Panel de Administración',
    admin_login: 'Panel de Administración',
    login: '🔑 Iniciar Sesión',
    username_label: 'Nombre de Usuario',
    password_label: 'Contraseña',
    enter_username: 'Ingrese nombre de usuario',
    enter_password: 'Ingrese contraseña',
    invalid_credentials: '❌ ¡Nombre de usuario o contraseña inválidos!',
    logout: '🚪 Cerrar Sesión',
    support_title: '🎫 Soporte',
    new_ticket: '✏️ Nuevo Ticket',
    subject: 'Asunto',
    message: 'Mensaje',
    priority: 'Prioridad',
    low: 'Baja',
    normal: 'Normal',
    high: 'Alta',
    urgent: 'Urgente',
    submit_ticket: '📤 Enviar Ticket',
    no_tickets: '📭 No se encontraron tickets',
    open: 'Abierto',
    closed: 'Cerrado',
    pending: 'Pendiente',
    about_title: 'ℹ️ Acerca de Nosotros',
    mission: '🎯 Nuestra Misión',
    features: '✨ Características Clave',
    contact: '📬 Contáctanos',
    email_label: 'Correo Electrónico',
    website: 'Sitio Web',
    telegram_bot: 'Telegram',
    version: 'Versión',
    copyright: 'Todos los derechos reservados',
    sync_success: '✅ Datos sincronizados correctamente',
    sync_error: '❌ Error de sincronización',
    logout_success: '👋 Has cerrado sesión',
    language_changed: '🌍 Idioma cambiado correctamente',
    payment_success: 'Pago exitoso',
    reward_claimed: 'Recompensa reclamada'
  },
  fr: {
    appName: 'Coin Mining',
    welcome: 'Bienvenue sur Coin Mining',
    choose_language: 'Choisir la langue',
    home: 'Accueil',
    wallet: 'Portefeuille',
    missions: 'Missions',
    profile: 'Profil',
    vip: 'VIP',
    referral: 'Parrainages',
    about: 'À propos',
    support: 'Support',
    settings: 'Paramètres',
    user_panel: 'Panneau Utilisateur',
    hello: 'Bonjour 👋',
    dear_user: 'Cher Utilisateur',
    total_balance: 'Solde Total',
    level: 'Niveau',
    logged_in: 'Connecté',
    select_coin: '💎 Sélectionnez une Cryptomonnaie à Miner',
    live_prices: '📊 Prix en Direct',
    connect_wallet: '🔗 Connecter le Portefeuille TON',
    wallet_balance: 'Solde du Portefeuille',
    disconnect: 'Déconnecter',
    payment: '💳 Paiement dans l\'App',
    pay: 'Payer',
    history: '📜 Historique des Transactions',
    free_miner: '⚡ Mineur Gratuit',
    active: 'Actif',
    start: 'Démarrer ▶',
    stop: 'Arrêter ⏹',
    rent_miners: '🏗️ Louer des Mineurs',
    rent: 'Louer',
    convert: '🔄 Convertir en TON',
    vip_club: '👑 Club VIP',
    current_level: 'Niveau Actuel',
    cost: 'Coût',
    upgrade: 'Améliorer',
    locked: '🔒 Verrouillé',
    daily_missions: '📅 Missions Quotidiennes',
    current_streak: 'Série Actuelle',
    day: 'Jour',
    reward: 'Récompense',
    claim: 'Réclamer 🎁',
    claimed: '✅ Réclamé',
    referral_title: '👥 Parrainages',
    referral_text: 'Invitez des amis et obtenez 1 TON de récompense et 10% de leurs dépôts',
    copy_link: '📋 Copier le Lien',
    share: 'Partager',
    telegram: '📨 Telegram',
    whatsapp: '💬 WhatsApp',
    instagram: '📱 Instagram',
    profile_title: '👤 Profil',
    username: 'Nom d\'utilisateur',
    email: 'E-mail',
    save_changes: '💾 Enregistrer les Modifications',
    change_password: '🔒 Changer le Mot de Passe',
    settings_title: '⚙️ Paramètres',
    change_language: '🌍 Changer de Langue',
    about_us: 'ℹ️ À Propos de Nous',
    feedback: '💬 Retours',
    send_feedback: '📤 Envoyer les Retours',
    admin_panel: '🛠️ Panneau d\'Administration',
    admin_login: 'Panneau d\'Administration',
    login: '🔑 Se Connecter',
    username_label: 'Nom d\'utilisateur',
    password_label: 'Mot de Passe',
    enter_username: 'Entrez le nom d\'utilisateur',
    enter_password: 'Entrez le mot de passe',
    invalid_credentials: '❌ Nom d\'utilisateur ou mot de passe invalide !',
    logout: '🚪 Se Déconnecter',
    support_title: '🎫 Support',
    new_ticket: '✏️ Nouveau Ticket',
    subject: 'Sujet',
    message: 'Message',
    priority: 'Priorité',
    low: 'Basse',
    normal: 'Normale',
    high: 'Haute',
    urgent: 'Urgente',
    submit_ticket: '📤 Envoyer le Ticket',
    no_tickets: '📭 Aucun ticket trouvé',
    open: 'Ouvert',
    closed: 'Fermé',
    pending: 'En attente',
    about_title: 'ℹ️ À Propos de Nous',
    mission: '🎯 Notre Mission',
    features: '✨ Fonctionnalités Clés',
    contact: '📬 Contactez-nous',
    email_label: 'E-mail',
    website: 'Site Web',
    telegram_bot: 'Telegram',
    version: 'Version',
    copyright: 'Tous droits réservés',
    sync_success: '✅ Données synchronisées avec succès',
    sync_error: '❌ Erreur de synchronisation',
    logout_success: '👋 Vous avez été déconnecté',
    language_changed: '🌍 Langue changée avec succès',
    payment_success: 'Paiement réussi',
    reward_claimed: 'Récompense réclamée'
  }
};

// ایجاد Context
const LanguageContext = createContext();

// Provider
export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'fa';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.fa[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook برای استفاده در کامپوننت‌ها
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;